# Generated by Django 4.0.2 on 2022-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(default='dark-souls.jpg', upload_to='media'),
        ),
    ]
