# Generated by Django 4.0.2 on 2022-04-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
    ]
