# Generated by Django 4.0.2 on 2022-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_firstname_member_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fullname',
        ),
        migrations.AddField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='Tharcisse', max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='MUNYANEZA', max_length=250),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(default='Tossen', max_length=250),
        ),
    ]
